name: Publish Release - Kasm
on:
  workflow_dispatch:

  push:
    branches:
    - main

jobs:
  Release:
    name: prepare release package
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
      with:
        ref: main

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ github.event.head_commit.message }}"
          prerelease: false
          title: "Release Build - ${{ github.event.head_commit.message }}"
          files: |
            **/*.tar.gz
